name:                QuantumChemistry
version:             0.1.0.0
github:              "githubuser/QuantumChemistry"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Package for help in Quantum Chemistry learning
# category:            Education

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/QuantumChemistry#readme>

dependencies:
- base >= 4.7 && < 5
- monad-par >= 0.3.5
- vector >= 0.12.3.1
- parallel >= 3.2.2.0
- deepseq >= 1.4.5.0
- gnuplot >= 0.5.7
library:
  source-dirs: src

executables:
  QuantumChemistry-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -eventlog
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - QuantumChemistry

tests:
  QuantumChemistry-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuantumChemistry
